directory: ~/Music
library: ~/.config/beets/musiclibrary.db
plugins: inline convert discogs embedart fetchart lyrics scrub info missing lastgenre edit ftintitle bandcamp
#bandcamp

import:
  move: yes
  write: yes

discogs:
  user_token: <discogs api key>

fetchart:
  google_key: <google api key>
  sources: google *

lyrics:
  fallback: ''
  google_API_key: <google api key>

album_fields:
    avgbitrate: |
        total = 0
        for item in items:
            total += item.bitrate
        return str(int((total / len(items)) / 1000)) + "kbps"

missing:
  format: $albumartist - $album - $title
  count: yes
  total: no

paths:
  default: $albumartist/[$year] $album [$format] %ifdef{$label} %ifdef{$catalognum}/$track - $title

lastgenre:
  canonical: yes
  count: 3
  fallback: ''
  prefer_specific: yes
  source: track
